force-app/main/default/objects/Lokace__c/Lokace__c.object-meta.xml
<CustomObject>
    <label>Lokace</label>
    <nameField>
        <label>Název Lokace</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lokace</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rezervace__c/Rezervace__c.object-meta.xml
<CustomObject>
    <label>Rezervace</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Kód Rezervace</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rezervace</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rezervace__c/fields/Pracovnik__c.field-meta.xml
<CustomField>
    <fullName>Pracovnik__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pracovník</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rezervace</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rezervace__c/fields/Udalost__c.field-meta.xml
<CustomField>
    <fullName>Udalost__c</fullName>
    <label>Událost</label>
    <referenceTo>Udalost__c</referenceTo>
    <relationshipLabel>Rezervace</relationshipLabel>
    <relationshipName>Rezervace</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Udalost__c/Udalost__c.object-meta.xml
<CustomObject>
    <label>Událost</label>
    <nameField>
        <label>Název Události</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Události</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Udalost__c/fields/Datum_Ud_losti__c.field-meta.xml
<CustomField>
    <fullName>Datum_Ud_losti__c</fullName>
    <label>Datum Události</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Udalost__c/fields/Lokace__c.field-meta.xml
<CustomField>
    <fullName>Lokace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lokace</label>
    <referenceTo>Lokace__c</referenceTo>
    <relationshipLabel>Události</relationshipLabel>
    <relationshipName>Udalosti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UdalostiController.cls
public with sharing class UdalostiController {
    @AuraEnabled(cacheable=true)
    public static List<UdalostiWrapper> getMojeUdalosti() {
        Id userId = UserInfo.getUserId();
        List<UdalostiWrapper> wrappers = new List<UdalostiWrapper>();
        for (Rezervace__c rezervace : [SELECT Id, Udalost__r.Id, Udalost__r.Name, Udalost__r.Lokace__r.Name, Udalost__r.Datum_Ud_losti__c
                                   FROM Rezervace__c
                                   WHERE Pracovnik__c = :userId]) {
            UdalostiWrapper wrapper = new UdalostiWrapper();
            wrapper.udalostId = rezervace.Udalost__r.Id;
            wrapper.lokaceName = rezervace.Udalost__r.Lokace__r.Name;
            wrapper.udalostName = rezervace.Udalost__r.Name;
            wrapper.udalostDate = rezervace.Udalost__r.Datum_Ud_losti__c;
            wrappers.add(wrapper);
        }
        return wrappers;
    }

    @AuraEnabled(cacheable=true)
    public static List<UdalostiWrapper> getUdalosti() {
        List<UdalostiWrapper> wrappers = new List<UdalostiWrapper>();
        for (Udalost__c udalost : [SELECT Id, Name, Lokace__r.Name, Datum_Ud_losti__c FROM Udalost__c]) {
            UdalostiWrapper wrapper = new UdalostiWrapper();
            wrapper.udalostId = udalost.Id;
            wrapper.lokaceName = udalost.Lokace__r.Name;
            wrapper.udalostName = udalost.Name;
            wrapper.udalostDate = udalost.Datum_Ud_losti__c;
            wrappers.add(wrapper);
        }
        return wrappers;
    }

    @AuraEnabled
    public static void prihlasitSeNaUdalost(Id udalostId) {
        Id userId = UserInfo.getUserId();
        Rezervace__c rezervace = new Rezervace__c(Udalost__c=udalostId, Pracovnik__c=userId);
        try{
            insert rezervace;
        }catch(Exception ex){
             System.debug(ex);
             throw new AuraHandledException(ex.getMessage());
        }
        
    }

    public class UdalostiWrapper {
        @AuraEnabled
        public Id udalostId;
        @AuraEnabled
        public String lokaceName;
        @AuraEnabled
        public String udalostName;
        @AuraEnabled
        public DateTime udalostDate;
    }
}