force-app/main/default/objects/Lokace__c/Lokace__c.object-meta.xml
<CustomObject>
    <label>Lokace</label>
    <nameField>
        <label>Název Lokace</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lokace</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lokace__c/fields/Kapacita__c.field-meta.xml
<CustomField>
    <fullName>Kapacita__c</fullName>
    <label>Kapacita</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rezervace__c/Rezervace__c.object-meta.xml
<CustomObject>
    <label>Rezervace</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Kód Rezervace</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rezervace</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rezervace__c/fields/Pracovnik__c.field-meta.xml
<CustomField>
    <fullName>Pracovnik__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pracovník</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rezervace</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rezervace__c/fields/Stav__c.field-meta.xml
<CustomField>
    <fullName>Stav__c</fullName>
    <defaultValue>&quot;Nová&quot;</defaultValue>
    <label>Stav</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nová</fullName>
            </value>
            <value>
                <fullName>Čeká schválení</fullName>
            </value>
            <value>
                <fullName>Schválená</fullName>
            </value>
            <value>
                <fullName>Zamítnuta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rezervace__c/fields/Udalost__c.field-meta.xml
<CustomField>
    <fullName>Udalost__c</fullName>
    <label>Událost</label>
    <referenceTo>Udalost__c</referenceTo>
    <relationshipLabel>Rezervace</relationshipLabel>
    <relationshipName>Rezervace</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Udalost__c/Udalost__c.object-meta.xml
<CustomObject>
    <label>Událost</label>
    <nameField>
        <label>Název Události</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Události</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Udalost__c/fields/Lokace__c.field-meta.xml
<CustomField>
    <fullName>Lokace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lokace</label>
    <referenceTo>Lokace__c</referenceTo>
    <relationshipLabel>Události</relationshipLabel>
    <relationshipName>Udalosti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RezervaceTriggerHelperTest.cls
@isTest
private class RezervaceTriggerHelperTest {
 // Pomocná metoda pro vytvoření testovacích dat: Lokace__c a Udalost__c
    private static void createTestData() {
        // Vytvoříme testovací Lokace__c záznam
        Lokace__c testLokace = new Lokace__c(Name='Test Lokace', Kapacita__c=1);
        insert testLokace;

        // Vytvoříme testovací Udalost__c záznam
        Udalost__c testUdalost = new Udalost__c(Name='Test Udalost', Lokace__c=testLokace.Id);
        insert testUdalost;
    }

    // Testovací metoda pro validateCapacity() - testování kapacity
    @IsTest
    static void testValidateCapacity() {
        createTestData();

        // Query pro získání testovací Udalost__c záznamu
        Udalost__c testUdalost = [SELECT Id FROM Udalost__c WHERE Name='Test Udalost' LIMIT 1];

        // Vytvoříme první testovací Rezervace__c záznam
        Rezervace__c rezervace1 = new Rezervace__c(Udalost__c=testUdalost.Id, Stav__c = 'Schválená');
        // Vytvoříme druhý testovací Rezervace__c záznam
        Rezervace__c rezervace2 = new Rezervace__c(Udalost__c= testUdalost.Id, Pracovnik__c = UserInfo.getUserId(), Stav__c = 'Schválená');

        Test.startTest();
        // Vložíme první testovací Rezervace__c záznam
        insert rezervace1;
        // Ověříme, že se úspěšně vložil
        System.assertEquals(1, [SELECT COUNT() FROM Rezervace__c]);

        // Pokus o vložení druheho testovacího Rezervace__c záznamu, který by měl překročit kapacitu
        String expectedErrorMessage = 'Kapacita je naplněná!';
        String errorHappened;
        try {
            insert rezervace2;
        } catch (DmlException e) {
            errorHappened = e.getDmlMessage(0);
        }
        Test.stopTest();
        // Ověříme, že chybová hláška je správná
        System.assertEquals(expectedErrorMessage, errorHappened);
    }
}